import { test } from 'node:test';
import assert from 'node:assert/strict';
import { outputs } from '../scripts/build.mjs';
import { loadBundle } from '../scripts/lib/load.mjs';
import { exists, read } from './helpers.mjs';

test('generated files match the data they come from', () => {
  const stale = [];
  for (const [file, content] of outputs(loadBundle())) {
    if (!exists(file) || read(file) !== content) stale.push(file);
  }
  assert.deepEqual(stale, [], 'run npm run build and commit the result');
});

test('generated pages say that they are generated', () => {
  for (const [file] of outputs(loadBundle())) {
    if (file.endsWith('.md') && !file.startsWith('README')) assert.match(read(file), /^<!-- Generated by scripts\/build\.mjs/, file);
  }
});

test('the READMEs list every pattern between their markers', () => {
  for (const file of ['README.md', 'README.ar.md']) {
    const text = read(file);
    for (const p of loadBundle().patterns) assert.ok(text.includes(`| ${p.id} |`), `${file} lists ${p.id}`);
  }
});
