// Generate the pattern pages, the glossary pages, and the website data bundle
// from the files in data/.
//
//   node scripts/build.mjs          write every generated file
//   node scripts/build.mjs --check  fail if any generated file is out of date
//
// Generated files are committed so that they read well on GitHub, and the check
// mode runs in CI so that they can never drift from the data.

import fs from 'node:fs';
import path from 'node:path';
import { loadBundle, readDiagram, root } from './lib/load.mjs';

const LANGS = ['en', 'ar'];
const LEVELS = ['foundation', 'enhanced', 'advanced'];

const WORDS = {
  en: {
    other: 'ar',
    otherName: 'العربية',
    generated: (src) => `<!-- Generated by scripts/build.mjs from ${src}. Edit the data, then run npm run build. -->`,
    catalogue: 'Pattern catalogue',
    catalogueIntro:
      'Twenty-eight patterns for recurring security architecture problems. Each one explains the problem, when to use it, the design, the controls at three levels, the decisions you must record, the trade-offs, the anti-patterns, how to verify it, and the threats it addresses.',
    levelsIntro:
      'Controls come in three levels: foundation, enhanced, and advanced. Put the foundation controls in place everywhere before going deeper anywhere.',
    mappingIntro:
      'Every control is mapped to NIST SP 800-53 Rev 5, CIS Controls v8.1, and ISO/IEC 27001:2022 Annex A, and every mapping is checked against the catalogues in data/catalogs.',
    advisorLink: 'To find the patterns your own system needs, answer the questions in the design advisor at',
    colNo: 'No.',
    colPattern: 'Pattern',
    colDomain: 'Domain',
    colSummary: 'Summary',
    domain: 'Domain',
    related: 'Related patterns',
    problem: 'The problem',
    useWhen: 'Use it when',
    design: 'The design',
    controls: 'Controls',
    decisions: 'Decisions to record',
    tradeoffs: 'Trade-offs',
    antipatterns: 'Anti-patterns to avoid',
    verify: 'How to verify it',
    threats: 'Threats it addresses',
    reference: 'Reference',
    name: 'Name',
    references: 'References',
    glossary: 'Glossary',
    glossaryIntro:
      'Short definitions of the terms used across Bunyan. Where a term matters most in one pattern, the last column links to it.',
    colTerm: 'Term',
    colDefinition: 'Definition',
  },
  ar: {
    other: 'en',
    otherName: 'English',
    generated: (src) => `<!-- Generated by scripts/build.mjs from ${src}. Edit the data, then run npm run build. -->`,
    catalogue: 'فهرس الأنماط',
    catalogueIntro:
      'ثمانية وعشرون نمطًا لمشكلات تتكرر في معمارية الأمن السيبراني، يشرح كل منها المشكلة ومتى تستخدمه والتصميم والضوابط على ثلاثة مستويات والقرارات التي يجب توثيقها والمفاضلات والأنماط الخاطئة وطريقة التحقق منه والتهديدات التي يتصدى لها.',
    levelsIntro:
      'تأتي الضوابط في ثلاثة مستويات هي الأساسي والمعزز والمتقدم، فطبّق الضوابط الأساسية في كل مكان قبل أن تتعمق في أي مكان.',
    mappingIntro:
      'يرتبط كل ضابط بمعايير NIST SP 800-53 Rev 5 وCIS Controls v8.1 وISO/IEC 27001:2022 Annex A، ويُتحقق من كل ارتباط آليًا مقابل الفهارس في المجلد data/catalogs.',
    advisorLink: 'لمعرفة الأنماط التي يحتاجها نظامك، أجب عن أسئلة مستشار التصميم عبر الرابط',
    colNo: 'الرقم',
    colPattern: 'النمط',
    colDomain: 'المجال',
    colSummary: 'الملخص',
    domain: 'المجال',
    related: 'أنماط ذات صلة',
    problem: 'المشكلة',
    useWhen: 'متى تستخدمه',
    design: 'التصميم',
    controls: 'الضوابط',
    decisions: 'قرارات يجب توثيقها',
    tradeoffs: 'المفاضلات',
    antipatterns: 'أنماط خاطئة يجب تجنبها',
    verify: 'كيف تتحقق منه',
    threats: 'التهديدات التي يتصدى لها',
    reference: 'المرجع',
    name: 'الاسم',
    references: 'المراجع',
    glossary: 'المصطلحات',
    glossaryIntro:
      'تعريفات قصيرة للمصطلحات المستخدمة في بُنيان، وإذا كان للمصطلح أهمية خاصة في نمط بعينه فإن العمود الأخير يشير إليه.',
    colTerm: 'المصطلح',
    colEnglish: 'المقابل الإنجليزي',
    colDefinition: 'التعريف',
  },
};

const fileOf = (p) => `${p.id}-${p.slug}.md`;
const cell = (s) => String(s).replace(/\|/g, '\\|');

function wrapRtl(lang, body) {
  if (lang !== 'ar') return body;
  return `<div dir="rtl" lang="ar">\n\n${body}\n</div>\n`;
}

function mappingLine(c) {
  return [
    ...c.nist.map((id) => `\`NIST ${id}\``),
    ...c.cis.map((id) => `\`CIS ${id}\``),
    ...c.iso.map((id) => `\`ISO A.${id}\``),
  ].join(' ');
}

function threatRows(bundle, p, lang) {
  const rows = [];
  for (const id of p.attack) {
    const t = bundle.catalogs.attack.techniques[id];
    rows.push(`| [${id}](${t.url}) | ${cell(t.name[lang])} |`);
  }
  for (const id of p.owasp) {
    const r = bundle.catalogs.owasp.risks[id];
    rows.push(`| [${id}](${r.url}) | ${cell(r.name[lang])} |`);
  }
  return rows;
}

export function patternPage(bundle, p, lang) {
  const w = WORDS[lang];
  const t = (v) => v[lang];
  const byId = new Map(bundle.patterns.map((x) => [x.id, x]));
  const out = [];
  out.push(`[${w.otherName}](../${w.other}/${fileOf(p)})`, '');
  out.push(`# ${p.id} ${t(p.title)}`, '');
  out.push(`> ${t(p.summary)}`, '');
  out.push(`| ${w.domain} | ${w.related} |`, '| --- | --- |');
  const related = p.related.map((id) => `[${id} ${cell(t(byId.get(id).title))}](${fileOf(byId.get(id))})`);
  out.push(`| ${t(bundle.meta.domains[p.domain])} | ${related.join(lang === 'ar' ? '، ' : ', ')} |`, '');
  out.push(`## ${w.problem}`, '', t(p.problem), '');
  out.push(`## ${w.useWhen}`, '');
  for (const u of p.useWhen) out.push(`- ${t(u)}`);
  out.push('');
  out.push(`## ${w.design}`, '');
  for (const para of p.design) out.push(t(para), '');
  out.push('```mermaid', readDiagram(p.id, lang), '```', '');
  out.push(`## ${w.controls}`, '');
  for (const level of LEVELS) {
    const list = p.controls.filter((c) => c.level === level);
    if (!list.length) continue;
    out.push(`### ${t(bundle.meta.levels[level])}`, '');
    for (const c of list) {
      out.push(`- **${t(c.name)}:** ${t(c.detail)}`);
      out.push(`  ${mappingLine(c)}`);
    }
    out.push('');
  }
  out.push(`## ${w.decisions}`, '');
  for (const d of p.decisions) out.push(`- ${t(d)}`);
  out.push('');
  out.push(`## ${w.tradeoffs}`, '');
  for (const d of p.tradeoffs) out.push(`- ${t(d)}`);
  out.push('');
  out.push(`## ${w.antipatterns}`, '');
  for (const d of p.antipatterns) out.push(`- ${t(d)}`);
  out.push('');
  out.push(`## ${w.verify}`, '');
  for (const d of p.verify) out.push(`- ${t(d)}`);
  out.push('');
  const rows = threatRows(bundle, p, lang);
  if (rows.length) {
    out.push(`## ${w.threats}`, '');
    out.push(`| ${w.reference} | ${w.name} |`, '| --- | --- |', ...rows, '');
  }
  out.push(`## ${w.references}`, '');
  for (const r of p.references) out.push(`- [${t(r.title)}](${r.url})`);
  out.push('');
  return `${w.generated(`data/patterns/${p.id}.json`)}\n\n${wrapRtl(lang, out.join('\n'))}`;
}

export function patternIndex(bundle, lang) {
  const w = WORDS[lang];
  const t = (v) => v[lang];
  const out = [];
  out.push(`[${w.otherName}](../${w.other}/README.md)`, '');
  out.push(`# ${w.catalogue}`, '');
  out.push(w.catalogueIntro, '');
  out.push(w.levelsIntro, '');
  out.push(w.mappingIntro, '');
  out.push(`| ${w.colNo} | ${w.colPattern} | ${w.colDomain} | ${w.colSummary} |`, '| --- | --- | --- | --- |');
  for (const p of bundle.patterns) {
    out.push(`| ${p.id} | [${cell(t(p.title))}](${fileOf(p)}) | ${t(bundle.meta.domains[p.domain])} | ${cell(t(p.summary))} |`);
  }
  out.push('');
  const site = bundle.meta.project.site;
  const link = `${site}${lang === 'ar' ? '?lang=ar' : ''}`;
  out.push(`${w.advisorLink} ${link}${lang === 'ar' ? '.' : '.'}`, '');
  return `${w.generated('data/patterns')}\n\n${wrapRtl(lang, out.join('\n'))}`;
}

const arabicSortKey = (s) => s.replace(/^ال/, '').replace(/^نموذج /, '');

export function glossaryPage(bundle, lang) {
  const w = WORDS[lang];
  const t = (v) => v[lang];
  const byId = new Map(bundle.patterns.map((x) => [x.id, x]));
  const terms = [...bundle.glossary].sort((a, b) =>
    lang === 'ar'
      ? arabicSortKey(a.term.ar).localeCompare(arabicSortKey(b.term.ar), 'ar')
      : a.term.en.localeCompare(b.term.en, 'en'),
  );
  const out = [];
  out.push(`[${w.otherName}](${w.other}.md)`, '');
  out.push(`# ${w.glossary}`, '');
  out.push(w.glossaryIntro, '');
  if (lang === 'ar') {
    out.push(`| ${w.colTerm} | ${w.colEnglish} | ${w.colDefinition} | ${w.colPattern} |`, '| --- | --- | --- | --- |');
  } else {
    out.push(`| ${w.colTerm} | ${w.colDefinition} | ${w.colPattern} |`, '| --- | --- | --- |');
  }
  for (const g of terms) {
    const p = g.pattern ? byId.get(g.pattern) : null;
    const link = p ? `[${p.id}](../patterns/${lang}/${fileOf(p)})` : '';
    if (lang === 'ar') out.push(`| **${cell(g.term.ar)}** | ${cell(g.term.en)} | ${cell(g.definition.ar)} | ${link} |`);
    else out.push(`| **${cell(g.term.en)}** | ${cell(g.definition.en)} | ${link} |`);
  }
  out.push('');
  return `${w.generated('data/glossary.json')}\n\n${wrapRtl(lang, out.join('\n'))}`;
}

// The README keeps a table of the patterns between two markers. The build
// rewrites only that block, so the rest of the README stays hand written.
const START = '<!-- patterns:start -->';
const END = '<!-- patterns:end -->';

export function readmeTable(bundle, lang) {
  const w = WORDS[lang];
  const t = (v) => v[lang];
  const rows = [`| ${w.colNo} | ${w.colPattern} | ${w.colDomain} |`, '| --- | --- | --- |'];
  for (const p of bundle.patterns) {
    rows.push(`| ${p.id} | [${cell(t(p.title))}](patterns/${lang}/${fileOf(p)}) | ${t(bundle.meta.domains[p.domain])} |`);
  }
  return rows.join('\n');
}

export function withReadmeTable(current, bundle, lang, file) {
  const a = current.indexOf(START);
  const b = current.indexOf(END);
  if (a < 0 || b < a) throw new Error(`${file} needs the ${START} and ${END} markers`);
  return `${current.slice(0, a + START.length)}\n\n${readmeTable(bundle, lang)}\n\n${current.slice(b)}`;
}

export function siteBundle(bundle) {
  return `${JSON.stringify(bundle)}\n`;
}

export function outputs(bundle) {
  const files = new Map();
  for (const lang of LANGS) {
    files.set(`patterns/${lang}/README.md`, patternIndex(bundle, lang));
    for (const p of bundle.patterns) files.set(`patterns/${lang}/${fileOf(p)}`, patternPage(bundle, p, lang));
    files.set(`glossary/${lang}.md`, glossaryPage(bundle, lang));
  }
  files.set('docs/data/bunyan.json', siteBundle(bundle));
  for (const [file, lang] of [['README.md', 'en'], ['README.ar.md', 'ar']]) {
    const full = path.join(root, file);
    if (fs.existsSync(full)) files.set(file, withReadmeTable(fs.readFileSync(full, 'utf8'), bundle, lang, file));
  }
  return files;
}

function main() {
  const check = process.argv.includes('--check');
  const files = outputs(loadBundle());
  const stale = [];
  for (const [rel, content] of files) {
    const full = path.join(root, rel);
    const current = fs.existsSync(full) ? fs.readFileSync(full, 'utf8') : null;
    if (current === content) continue;
    if (check) stale.push(rel);
    else {
      fs.mkdirSync(path.dirname(full), { recursive: true });
      fs.writeFileSync(full, content);
      console.log(`wrote ${rel}`);
    }
  }
  if (check) {
    if (stale.length) {
      console.error(`These generated files are out of date. Run npm run build and commit the result:\n  ${stale.join('\n  ')}`);
      process.exitCode = 1;
    } else {
      console.log(`${files.size} generated files are up to date.`);
    }
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.join(root, 'scripts', 'build.mjs')) main();

